### ISSUE TITLE
Agentspeak programming

### ISSUE THREAD

**Issue by Simon-Yacoub** [NMAI-lab/saviRoomba#13]
Program IR and bluetooth sensors with savi_ros_bdi agent.

**Comment by pgavigan** [comment]
First draft AgentSpeak code has been added to the repository. This code will need to be modified based on the resolution of issue #16, as the AgentSpeak code needs to perceive the perceptions that are generated by the perception translator. This development is dependent on issue #16 being resolved.

**Comment by pgavigan** [comment]
Working Agent program has been provided and tested using relative navigation without the beacons.
