### ISSUE TITLE
Update to perception translator

### ISSUE THREAD

**Issue by pgavigan** [NMAI-lab/saviRoomba#16]
The perception translator needs to be updated. The perception translator at this location should be used as a template: https://github.com/NMAI-lab/AirSimNavigatingCar/tree/master/catkin_ws/src/translators/scripts

The perception translator node should closely follow the design of the node at the above link.

Here is what the new translator needs to do:

Subscribe to the following topics: battery state (the current version in this repository already does), beacons (being added to resolve issue #15), IR sensor (being added for issue #14), bumper sensor (from create_autonomy), any other needed perceptions (are there any others?)

The node should publish to the perceptions topic a string containing a complete perception for each sensor. It should look something like this:
"battery(...) irWall(.....) beacon(.....) bumper(.....)"

The battery perception should simply pass the battery state of charge.
The irWall perception should pass a range (I am assuming that is what data is available, this may need to be updated)
The beacon perception should include the beacon ID, range, or whatever else the beacon node gives us
The bumper perception is likely just a boolean

It may be acceptable to publish the bumper perception separately.

**Comment by pgavigan** [comment]
A further comment on this issue. The battery perception can simply be the battery state of charge. There is no need for a separate battery node, as the relevant data is provided by the create_autonomy node. The perception translator can subscribe to battery/charge_ratio (provided by create_autonomy) and publish battery(State) to perceptions. State is simply the charge ratio provided by create_autonomy.

**Comment by Simon-Yacoub** [comment]
Yes I noticed that was how it was done before but I would prefer to have the battery as a sensor so I can have one central perception translator that will read from all /sensor/... topics. See the new issue I have with pull request https://github.com/NMAI-lab/saviRoomba/issues/19

**Comment by Simon-Yacoub** [comment]
For the irWall() perception does this seem like a good format:

"irWall(close)" -> less than 23 cm from the wall
"irWalll(far)" -> more than 28 cm from the wall
"irWall(perfect)" -> between 23-28 cm from the wall

or do you think I will need more ranges?

**Comment by Simon-Yacoub** [comment]
Also I realize that I will be able to do the same thing i did for the battery with the bumper since createautonomy also creates the bumper topic for me aswell

**Comment by Simon-Yacoub** [comment]
I have added and tested scripts that output raw data from the IR, bluetooth and bumper sensors. Now all I have to do is tweak the perceptionTranslator so it give information like so:

irWall(distance, angle)
bumper(touching)
beacon(distance, node)
